### ISSUE TITLE
DARK MODE

### ISSUE THREAD

**Issue by harisdev-netizen** [harisdev-netizen/connect#14]
addition of dark mode, which can be changed according to the user.

**Comment by abitsalihu** [comment]
@harisdev-netizen I would like to help with this issue. :)

**Comment by harisdev-netizen** [comment]
> @harisdev-netizen I would like to help with this issue. :)

Added you 👍

**Comment by abitsalihu** [comment]
@harisdev-netizen will do a push/review tomorrow. :)

**Comment by harisdev-netizen** [comment]
> @harisdev-netizen will do a push/review tomorrow. :)

Sure. Looking forward to it.

**Comment by nupur-jeswani** [comment]
Hey, I would like to work on this issue!

**Comment by harisdev-netizen** [comment]
> Hey, I would like to work on this issue!

Sure.

**Comment by harisdev-netizen** [comment]
> Hey, I would like to work on this issue!

Added you :)
